version: '3.8'

services:
  omnidata-hub:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: omnidata_platform
    ports:
      - "8080:8080"
    restart: always
    environment:
      - PORT=8080
      - ENV=production
